config/routes.rb
Beertap::Application.routes.draw do
  resources :followings

  resources :beers do
    collection do
      get 'search'
    end
  end

  resources :beer_profiles
  root 'beers#search'
  get 'beer_profiles/users/:id' => 'beer_profiles#users'

  post "user/guest_sign_in"
  devise_for :users
end

app/models/following.rb
class Following < ActiveRecord::Base

  belongs_to :user
  belongs_to :followed, :class_name => 'User'

end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_any_user
  before_action :set_following, only: [:show, :edit, :update, :destroy]

  # GET /followings
  def index
    @followings = current_user.followings
    @followers = current_user.followers
  end

  # GET /followings/1
  def show
  end

  # GET /followings/new
  def new
    following_ids = current_user.followings.select(&:id)
    following_ids << current_user.id
    @users = User.where("email LIKE ? and id not in (?)", "%#{params[:email]}%", following_ids)
    @following = Following.new
  end

  # POST /followings
  def create
    @following = Following.new(following_params)
    @following.user_id = current_user.id

    if @following.save
      redirect_to action: 'index' , notice: 'Following was successfully created.'
    else
      render action: 'new'
    end
  end

  # DELETE /followings/1
  def destroy
    @following.destroy
    redirect_to followings_url
  end

  def search
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_following
      @following = Following.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def following_params
      params.require(:following).permit(:user_id, :followed_id)
    end
end

app/views/followings/index.html.erb
<div>
  <%= form_tag new_following_path, :method => :get do %>
    <input placeholder="Search for Friends" type="text" name="email" class="form-text lg4-lg6 md1-md3" />
    <input type="submit" value="Search" class="button friends-search push-effect lg7-lg8 md4" />
  <% end %>
</div>
<div class="clearfix"></div>
<div class="friends">
<h1>You are following:</h1>
<div class="clearfix"></div>
<div>
  <% if @followings.size == 0 %>
    You are following no one.
  <% else %>
    <% @followings.each do |following| %>
       <div class="following box clearfix">
       <%= link_to following.followed.email, "/beer_profiles/users/#{following.followed_id}" %>
        <%= link_to 'Unfollow', following, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button unfollow push-effect lg7-lg8 md4" %>
      </div>
    <% end %>
  <% end %>
</div>

<h1>People following you:</h1>
<div>
  <% if @followers.size == 0 %>
    No one is following you.
  <% else %>
    <% @followers.each do |follower| %>
      <div class="following box clearfix">
<%= link_to follower.email, "/beer_profiles/users/#{follower.id}" %>
</div>
    <% end %>
  <% end %>
</div>
</div><br>

app/views/followings/new.html.erb
<div class="friends">
<h1>New following</h1>

<% @users.each do |user| %>
  <%= form_tag followings_path do %>
  <div class="following box clearfix">
    <%= hidden_field_tag "following[followed_id]", user.id %>
    <%= user.email %>
    <%= submit_tag "Add ", :class => "button push-effect lg7-lg8 md4" %>
</div>
  <% end %>
<% end %>
<%= link_to 'Back', followings_path, :class => "button add push-effect lg1-lg2" %>
</div>