config/routes.rb
Beertap::Application.routes.draw do
  resources :followings

  resources :beers do
    collection do
      get 'search'
    end
  end

  resources :beer_profiles
  root 'beers#search'
  get 'beer_profiles/users/:id' => 'beer_profiles#users'

  post "user/guest_sign_in"
  devise_for :users
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  has_many :beer_profiles
end

app/controllers/beers_controller.rb
require 'net/http'

class BeersController < ApplicationController

  before_filter :authenticate_any_user

  def index
  end

  def create
    @beer = Beer.new(beer_params)
    if @beer.save
      redirect_to(new_beer_profile_path + "?beer_id=" + @beer.id.to_s)
    else
      redirect_to :new, :flash => "There was a problem saving the beer."
    end
  end

  def search
    unless params[:q].nil?
      uri = URI("https://api.untappd.com/v4/search/beer")
      untapped_params = { :q => params[:q],
                 :client_id => ENV['UNTAPPED_CLIENT_ID'],
                 :client_secret => ENV['UNTAPPED_CLIENT_SECRET'] }
      uri.query = URI.encode_www_form(untapped_params)

      @result = Net::HTTP.get_response(uri)

      if @result.is_a?(Net::HTTPSuccess)
        @json = JSON.parse(@result.body)
        @beer = Beer.new
      end
    end
  end

  private

  def beer_params
    params.require(:beer).permit(:name, :style, :brewery, :abv, :image_path)
  end

end

app/helpers/beer_helper.rb
module BeerHelper
end

app/views/beers/_initial_search.html.erb
<div class="lg2-lg7">
  <div class="hero clearfix">
  <a href="/"><img src="/images/logo.png" alt="Beer Tap"></a>
  <h1>Your Personal Beer Journal</h1>
  </div>
</div>
<div class="clearfix"></div>
<div class="search-landing-page clearfix lg2-lg7 md-all sm-all">
  <h3>Search for a beer to profile:</h3>

  <%= form_tag search_beers_path, :method => :get do%>
    <%= text_field_tag 'q', '', :class=> "form-text lg2-lg5"%>
    <%= submit_tag "Search for beer", :class => "button push-effect beer-search lg6-lg7" %>
  <% end %>
</div>

app/views/beers/_search_again.html.erb
<div class="search-container clearfix">
<%= form_tag search_beers_path, :method => :get do %>
  <%= text_field_tag 'q', params[:q], :class => "form-text lg1-lg5" %>
  <%= submit_tag "Search for beer", :class => "button push-effect lg6-lg8" %>
<% end %>
</div>

app/views/beers/search.html.erb
<% if @json.nil? %>
  <%= render partial: 'initial_search' %>
<% else %>
  <%= render partial: 'search_again' %>
<% end %>

<% unless @json.nil? %>

  <div class="search-results box clearfix">
      <h2>Search Results</h2>
      <div class="results-container">
      <% @json['response']['beers']['items'].each do |item| %>
      <div class="individual-result">
        <img src="<%= item['beer']['beer_label'] %>" />
		    <div class="producer">
		      <h3><%= item['beer']['beer_name'] %></h3>
          	  <h4><%= item['brewery']['brewery_name'] %></h4>
		    </div>
        <%= form_for @beer do |f| %>
          <%= f.hidden_field :name, :value => item['beer']['beer_name'] %>
          <%= f.hidden_field :style, :value => item['beer']['beer_style']%>
          <%= f.hidden_field :brewery, :value => item['brewery']['brewery_name'] %>
          <%= f.hidden_field :abv, :value => item['beer']['beer_abv'] %>
          <%= f.hidden_field :image_path, :value => item['beer']['beer_label'] %>
        <% end %>
      </div>
    <% end %>
    <div class="clearfix"></div>
    <div>
      <div class="producer help">
		    <h3>Can't find your beer?</h3>
        	<h4>Add <%= params['q'] %> to your journal.</h4>
      </div>
      <%= form_for @beer do |f| %>
        <%= f.hidden_field :name, :value => params['q'] %>
      <% end %>
    </div>
</div>
  </div>
<% end %>

<script type="text/javascript">
  $(function() {
    $('.individual-result').click(function(){
      $(this).find('form').submit()
    })
  })
</script>