config/routes.rb
Beertap::Application.routes.draw do
  resources :followings

  resources :beers do
    collection do
      get 'search'
    end
  end

  resources :beer_profiles
  root 'beers#search'
  get 'beer_profiles/users/:id' => 'beer_profiles#users'

  post "user/guest_sign_in"
  devise_for :users
end

app/models/beer_profile.rb
class BeerProfile < ActiveRecord::Base
  belongs_to :user
  belongs_to :beer

  def flavors
    [flavor_esters, flavor_alcoholic, flavor_citrus, flavor_hoppy, flavor_floral, flavor_spicy, flavor_malty, flavor_toffee, flavor_burnt, flavor_sweet, flavor_sour, flavor_bitter, flavor_astringent, flavor_full_bodied, flavor_lingers]
  end
end

app/controllers/beer_profiles_controller.rb
class BeerProfilesController < ApplicationController
  before_action :set_beer_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_any_user, except: [:users, :show]

  def index
    @beer_profiles = BeerProfile.where(:user_id => current_user.id)
    @user = current_user
  end

  def show
    @beer_profile = BeerProfile.find(params[:id])
  end

  def new
    @beer = Beer.where(:id => params['beer_id']).first
    if @beer.nil?
      redirect_to action: :index
    else
      @beer_profile = BeerProfile.new
      @beer_profile.beer_id = @beer[:id]
      @beer_profile.attributes = beer_properties(@beer)
      @from_untapped = @beer.brewery.present?
    end
  end

  def edit
    @beer_profile = BeerProfile.where(:user_id => current_user.id, :id => params[:id]).first
    @beer = Beer.find(@beer_profile.beer_id)
    @from_untapped = @beer.brewery.present?
  end

  def create
    @beer_profile = BeerProfile.new(beer_profile_params)
    @beer = Beer.find(@beer_profile.beer_id)
    @beer_profile.attributes = beer_properties(@beer) unless @beer.brewery.nil?
    @beer_profile.user_id = current_user.id

    if @beer_profile.save
      redirect_to @beer_profile, notice: 'Beer profile was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @beer_profile.update(beer_profile_params)
      redirect_to @beer_profile, notice: 'Beer profile was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @beer_profile.destroy
    redirect_to beer_profiles_url
  end

  def users
    @beer_profiles = BeerProfile.where(:user_id => params[:id])
    @user = User.where(:id => params[:id]).first

    render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_profile
      @beer_profile = BeerProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_profile_params
      params.require(:beer_profile).permit(:appearance_head_size, :appearance_head_texture, :appearance_head_color, :appearance_head_retention, :appearance_lacing, :appearance_body_opacity, :appearance_body_carbonation, :appearance_color, :appearance_notes, :aroma_malt, :aroma_hops, :aroma_esters, :aroma_phenols, :aroma_bitterness, :aroma_flavor_grain, :aroma_flavor_hops, :aroma_flavor_fruit, :aroma_flavor_herbs, :aroma_flavor_funk, :aroma_flavor_mineral, :aroma_flavor_other, :aroma_notes, :taste_malt, :taste_hops, :taste_esters, :taste_phenols, :taste_bitterness, :taste_flavor_grain, :taste_flavor_hops, :taste_flavor_fruit, :taste_flavor_herbs, :taste_flavor_funk, :taste_flavor_mineral, :taste_flavor_other, :taste_notes, :mouth_body, :mouth_carbonation, :mouth_alcohol, :mouth_richness, :mouth_astringency, :mouth_finish, :mouth_notes, :flavor_esters, :flavor_alcoholic, :flavor_citrus, :flavor_hoppy, :flavor_floral, :flavor_spicy, :flavor_malty, :flavor_toffee, :flavor_burnt, :flavor_sweet, :flavor_sour, :flavor_bitter, :flavor_astringent, :flavor_full_bodied, :beer_id, :flavor_lingers, :image_path, :name, :style, :brewery, :abv, :rating, :notes)
    end

    def beer_properties(beer)
      {
        name: beer.name,
        style: beer.style,
        brewery: beer.brewery,
        abv: beer.abv,
        image_path: beer.image_path
      }
    end
end

app/helpers/beer_profile_helper.rb
module BeerProfileHelper

  STRENGTH_ATTRIBUTE = %w(Faint Average Strong)

  PROFILE_ATTRIBUTES = {
    size: %w(Spare Small Average Large Huge),
    texture: %w(Rocky Creamy Frothy Fizzy),
    color: %w(White Yellow Tan Dark),
    retention: %w(Short Long),
    lacing: %w(None Faint Good Great),
    opacity: %w(Clear Hazy Cloudy Opaque),
    body_carbonation: %w(Flat Light Average Heavy),
    malt: STRENGTH_ATTRIBUTE,
    aroma_hops: STRENGTH_ATTRIBUTE,
    esters: STRENGTH_ATTRIBUTE,
    phenols: STRENGTH_ATTRIBUTE,
    bitterness: STRENGTH_ATTRIBUTE,
    grain: %w(Bread/Biscuit Burnt Caramel Cereal Chocolate Coffee/Espresso Malt Nutty Oat Roasted Rye Toffee),
    flavor_hops: %w(Dank Flowers Geranium Grapefruit Herbal Lemon Lemongrass Orange\ Blossom Pine Resinous Spicy Perfume),
    fruit: %w(Apple Apricot Bananna Blackberry Blueberry Cassis Cherry Cranberry Orange Peach Raspberry Strawberry Plum Prune Pear Pineapple),
    herbs: %w(Anise Caraway Chamomille Clove Cinnamon Coriander Grains\ of\ Paradise Lavender Orange\ Peel Rose\ Hips Sassafras Nutmeg),
    funk: %w(Barnyard Horse Leather Wood Sweat Cheese Vinegar),
    mineral: %w(Bloody Chalk Copper Iron Salty),
    other: %w(Bubble\ Gum Soy\ Sauce Licorice Cola Tobacoo Eggs),
    body: %w(Light Medium Full),
    mouth_carbonation: STRENGTH_ATTRIBUTE,
    alcohol: STRENGTH_ATTRIBUTE,
    richness: %w(Thin Creamy Chewy),
    astringency: STRENGTH_ATTRIBUTE,
    finish: %w(Sweet Medium Dry)
  }

  COLOR_ATTRIBUTES = {
    1 => {
      name: 'Pale Straw',
      hex_value: 'F9FF2D'
    },
    2 => {
      name: 'Straw',
      hex_value: 'FEEF20'
    },
    3 => {
      name: 'Pale Gold',
      hex_value: 'FFDB34'
    },
    4 => {
      name: 'Deep Gold',
      hex_value: 'FFA42F'
    },
    5 => {
      name: 'Pale Amber',
      hex_value: 'FF9A2F'
    },
    6 => {
      name: 'Medium Amber',
      hex_value: 'E27750'
    },
    7 => {
      name: 'Deep Amber',
      hex_value: '9D4B33'
    },
    8 => {
      name: 'Amber-Brown',
      hex_value: '883D3D'
    },
    9 => {
      name: 'Brown',
      hex_value: '60302D'
    },
    10 => {
      name: 'Ruby Brown',
      hex_value: '4E3A29'
    },
    11 => {
      name: 'Deep Brown',
      hex_value: '392F2E'
    },
    12 => {
      name: 'Black',
      hex_value: '31302C'
    }
  }

  def profile_field(form, field, profile, from_untapped)
    if from_untapped
      profile.send(field)
    else
      form.text_field field
    end
  end

  def appearance_blank?
    appearance_head_blank? && appearance_body_blank? && @beer_profile.appearance_notes.blank?
  end

  def appearance_head_blank?
    @beer_profile.appearance_head_size.blank? &&
      @beer_profile.appearance_head_texture.blank? &&
      @beer_profile.appearance_head_color.blank? &&
      @beer_profile.appearance_head_retention.blank?
  end

  def appearance_body_blank?
    @beer_profile.appearance_body_opacity.blank? &&
      @beer_profile.appearance_body_carbonation.blank? &&
      @beer_profile.appearance_color.blank?
  end
  
  def aroma_section_blank?
    @beer_profile.aroma_malt.blank? &&
      @beer_profile.aroma_hops.blank? &&
      @beer_profile.aroma_esters.blank? &&
      @beer_profile.aroma_phenols.blank? &&
      @beer_profile.aroma_bitterness.blank?
  end

  def aroma_flavor_section_blank?
    @beer_profile.aroma_flavor_grain.blank? &&
      @beer_profile.aroma_flavor_hops.blank? &&
      @beer_profile.aroma_flavor_fruit.blank? &&
      @beer_profile.aroma_flavor_herbs.blank? &&
      @beer_profile.aroma_flavor_funk.blank? &&
      @beer_profile.aroma_flavor_mineral.blank? &&
      @beer_profile.aroma_flavor_other.blank?
  end
  def taste_section_blank?
    taste_flavor_section_blank? &&
      @beer_profile.taste_notes.blank?
      @beer_profile.taste_malt.blank?
      @beer_profile.taste_hops.blank?
      @beer_profile.taste_esters.blank?
      @beer_profile.taste_phenols.blank?
      @beer_profile.taste_bitterness.blank?
  end

  def taste_flavor_section_blank?
    @beer_profile.taste_flavor_grain.blank? &&
      @beer_profile.taste_flavor_hops.blank? &&
      @beer_profile.taste_flavor_fruit.blank? &&
      @beer_profile.taste_flavor_herbs.blank? &&
      @beer_profile.taste_flavor_funk.blank? &&
      @beer_profile.taste_flavor_mineral.blank? &&
      @beer_profile.taste_flavor_other.blank?
  end

  def mouthfeel_section_blank?
    @beer_profile.mouth_body.blank? &&
      @beer_profile.mouth_carbonation.blank? &&
      @beer_profile.mouth_alcohol.blank? &&
      @beer_profile.mouth_richness.blank? &&
      @beer_profile.mouth_astringency.blank? &&
      @beer_profile.mouth_finish.blank? &&
      @beer_profile.mouth_notes.blank?
  end

end

app/views/beer_profiles/_radio_group.html.erb
<% BeerProfileHelper::PROFILE_ATTRIBUTES[attribute].each do |option| %>
  <% label_group ||= nil %>
  <% label_class = cycle('lg4', 'lg5', 'lg6', 'lg7', 'lg8') unless label_group.nil? %>
  <%= f.radio_button field, option %>
  <%= f.label field, option, value: option, class: label_class %>
<% end %>
<% reset_cycle %>

app/views/beer_profiles/_slider.html.erb
<% value = @beer_profile.send(field) || 1 %>
<span class='slider-value'><%= value %></span>
<%= f.range_field field, in: 1..5, value: value, class: 'rating-slider' %>

app/views/beer_profiles/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @beer_profile %> |
<%= link_to 'Back', beer_profiles_path %>

app/views/beer_profiles/index.html.erb
<% if @beer_profiles.empty? %>
  <h1><%= current_user.id == @user.id ? "You Haven't" : "#{@user.email} Has Not" %> Profiled Any Beers Yet</h1>
  <% if current_user.id == @user.id %>
    <%= render partial: 'beers/search_again' %>
  <% end %>
<% else %>
  <div class="profiled-beers-list">
  <h1><%= current_user.id == @user.id ? "My" : "#{@user.email}'s" %> Profiled Beers</h1>
    <div class="search-results box clearfix lg-all">
      <% @beer_profiles.each do |beer_profile| %>
        <a href="<%= beer_profile_path(beer_profile) %>">
          <div class="individual-result" <%= cycle 'lg1-lg4 md-all sm-all', 'lg5-lg8 md-all sm-all' %>">
            <% image_path = beer_profile.image_path.nil? ? 'https://untappd.s3.amazonaws.com/site/assets/images/temp/badge-beer-default.png' : beer_profile.image_path %>
            <img src="<%= image_path %>" />
            <div class="producer">
              <h3><%= beer_profile.name %></h3>
              <% unless beer_profile.brewery.nil? %>
                <h4><%= beer_profile.brewery %></h4>
              <% end %>
            </div>
          </div>
        </a>
      <% end %>
    </div>
</div>
<% end %>

app/views/beer_profiles/new.html.erb
<%= render 'form' %>

app/views/beer_profiles/show.html.erb
<p id="notice"><%= notice %></p>
<h1>A Selected Entry From <%= current_user.id == @beer_profile.user_id ? "My" : link_to("#{@beer_profile.user.email}'s", "/beer_profiles/users/#{@beer_profile.user.id}") %> Beer Journal</h1>
<div id="result" class="journal-entry-single">
  <div class="box beer-type-profile lg1-lg4 md1-md2 sm-all">
    <h2>Profile</h2>

    <div class="secondary-section logo-name">
      <img src="<%= @beer_profile.image_path %>" />
      <h1><%= @beer_profile.name %></h1>
      <h4><%= @beer_profile.brewery %></h4>
    </div>
    <div class="secondary-section">
      <h3>Style</h3>
      <%= @beer_profile.style %>
    </div>
    <div class="secondary-section">

    </div>
    <div class="secondary-section">
      <h3>ABV</h3>
      <%= @beer_profile.abv %>%
    </div>
    <div class="secondary-section">
      <h3>Rating</h3>
      <%= @beer_profile.rating %>
    </div>
    <% unless @beer_profile.notes.blank? %>
      <div class="secondary-section">
        <h3>Notes</h3>
        <%= @beer_profile.notes %>
      </div>
    <% end %>
  </div>

  <div class="box lg5-lg8 md3-md4 sm-all">
    <h2>Flavor Chart</h2>
    <div class="dac">
      <canvas id="flavor-wheel" width="400" height="400"></canvas>
    </div>
  </div>

  <div class="box lg1-lg4 md1-md2 sm-all">
    <h2>Apperance</h2>
    <% unless appearance_head_blank? %>
      <div class="secondary-section">
        <h3>Head</h3>
        <% unless @beer_profile.appearance_head_size.blank? %>
          <div class="tertiary-section">
            <h4>size</h4>
            <%= @beer_profile.appearance_head_size %>
          </div>
        <% end %>

        <% unless @beer_profile.appearance_head_texture.blank? %>
          <div class="tertiary-section">
            <h4>texture</h4>
            <%= @beer_profile.appearance_head_texture %>
          </div>
        <% end %>

        <% unless @beer_profile.appearance_head_color.blank? %>
          <div class="tertiary-section">
            <h4>color</h4>
            <%= @beer_profile.appearance_head_color %>
          </div>
        <% end %>

        <% unless @beer_profile.appearance_head_retention.blank? %>
          <div class="tertiary-section">
            <h4>retention</h4>
            <%= @beer_profile.appearance_head_retention %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% unless @beer_profile.appearance_lacing.blank? %>
      <div class="secondary-section">
        <h3>lacing</h3>
        <%= @beer_profile.appearance_lacing %>
      </div>
    <% end %>

    <% unless appearance_body_blank? %>
      <div class="secondary-section">
        <h3>Body</h3>
        <% unless @beer_profile.appearance_body_opacity.blank? %>
          <div class="tertiary-section">
            <h4>opacity</h4>
            <%= @beer_profile.appearance_body_opacity %>
          </div>
        <% end %>

        <% unless @beer_profile.appearance_body_carbonation.blank? %>
          <div class="tertiary-section">
            <h4>carbonation</h4>
            <%= @beer_profile.appearance_body_carbonation %>
          </div>
        <% end %>

        <% unless @beer_profile.appearance_color.blank? %>
          <div class="tertiary-section">
            <h4>color</h4>
            <%= BeerProfileHelper::COLOR_ATTRIBUTES[@beer_profile.appearance_color][:name] %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% unless @beer_profile.appearance_notes.blank? %>
      <div class="secondary-section">
        <h3>notes</h3>
        <%= @beer_profile.appearance_notes %>
      </div>
    <% end %>

    <% if appearance_blank? %>
      No thoughts? Tell us how your heart feels.
    <% end %>
  </div>


  <div class="box lg5-lg8 md3-md4 sm-all">
  <h2>Aroma</h2>
    <% unless @beer_profile.aroma_malt.blank? %>
      <div class="secondary-section">
        <h3>malt</h3>
        <%= @beer_profile.aroma_malt %>
      </div>
    <% end %>

    <% unless @beer_profile.aroma_hops.blank? %>
      <div class="secondary-section">
        <h3>hops</h3>
        <%= @beer_profile.aroma_hops %>
      </div>
    <% end %>

    <% unless @beer_profile.aroma_esters.blank? %>
      <div class="secondary-section">
        <h3>esters</h3>
        <%= @beer_profile.aroma_esters %>
      </div>
    <% end %>

    <% unless @beer_profile.aroma_phenols.blank? %>
      <div class="secondary-section">
        <h3>phenols</h3>
        <%= @beer_profile.aroma_phenols %>
      </div>
    <% end %>

    <% unless @beer_profile.aroma_bitterness.blank? %>
      <div class="secondary-section">
        <h3>bitterness</h3>
        <%= @beer_profile.aroma_bitterness %>
      </div>
    <% end %>

    <% unless aroma_flavor_section_blank? %>
      <div class="secondary-section">
        <h3>Flavor</h3>
        <% unless @beer_profile.aroma_flavor_grain.blank? %>
          <div class="tertiary-section">
            <h4>grain</h4>
            <%= @beer_profile.aroma_flavor_grain %>
          </div>
        <% end %>

        <% unless @beer_profile.aroma_flavor_hops.blank? %>
          <div class="tertiary-section">
            <h4>hops</h4>
            <%= @beer_profile.aroma_flavor_hops %>
          </div>
        <% end %>

        <% unless @beer_profile.aroma_flavor_fruit.blank? %>
          <div class="tertiary-section">
            <h4>fruit</h4>
            <%= @beer_profile.aroma_flavor_fruit %>
          </div>
        <% end %>

        <% unless @beer_profile.aroma_flavor_herbs.blank? %>
          <div class="tertiary-section">
            <h4>herbs</h4>
            <%= @beer_profile.aroma_flavor_herbs %>
          </div>
        <% end %>

        <% unless @beer_profile.aroma_flavor_funk.blank? %>
          <div class="tertiary-section">
            <h4>funk</h4>
            <%= @beer_profile.aroma_flavor_funk %>
          </div>
        <% end %>

        <% unless @beer_profile.aroma_flavor_mineral.blank? %>
          <div class="tertiary-section">
            <h4>mineral</h4>
            <%= @beer_profile.aroma_flavor_mineral %>
          </div>
        <% end %>

        <% unless @beer_profile.aroma_flavor_other.blank? %>
          <div class="tertiary-section">
            <h4>other</h4>
            <%= @beer_profile.aroma_flavor_other %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% unless @beer_profile.aroma_notes.blank? %>
      <div class="secondary-section">
        <h3>Notes</h3>
        <strong>notes</strong>
        <%= @beer_profile.aroma_notes %>
      </div>
    <% end %>

    <% if aroma_section_blank? %>
      No thoughts? Tell us how your heart feels.
    <% end %>
  </div>

  <div class="box lg1-lg4 md1-md2 sm-all">
    <h2>Taste</h2>
    <% unless @beer_profile.taste_malt.blank? %>
      <div class="secondary-section">
        <h3>malt</h3>
        <%= @beer_profile.taste_malt %>
      </div>
    <% end %>

    <% unless @beer_profile.taste_hops.blank? %>
      <div class="secondary-section">
        <h3>hops</h3>
        <%= @beer_profile.taste_hops %>
      </div>
    <% end %>

    <% unless @beer_profile.taste_esters.blank? %>
      <div class="secondary-section">
        <h3>esters</h3>
        <%= @beer_profile.taste_esters %>
      </div>
    <% end %>

    <% unless @beer_profile.taste_phenols.blank? %>
      <div class="secondary-section">
        <h3>phenols</h3>
        <%= @beer_profile.taste_phenols %>
      </div>
    <% end %>

    <% unless @beer_profile.taste_bitterness.blank? %>
      <div class="secondary-section">
        <h3>bitterness</h3>
        <%= @beer_profile.taste_bitterness %>
      </div>
    <% end %>

    <div class="secondary-section">
      <% unless taste_flavor_section_blank? %>?
        <h3>Flavor</h3>
        <% unless @beer_profile.taste_flavor_grain.blank? %>
          <div class="tertiary-section">
            <h4>grain</h4>
            <%= @beer_profile.taste_flavor_grain %>
          </div>
        <% end %>

        <% unless @beer_profile.taste_flavor_hops.blank? %>
          <div class="tertiary-section">
            <h4>hops</h4>
            <%= @beer_profile.taste_flavor_hops %>
          </div>
        <% end %>

        <% unless @beer_profile.taste_flavor_fruit.blank? %>
          <div class="tertiary-section">
            <h4>fruit</h4>
            <%= @beer_profile.taste_flavor_fruit %>
          </div>
        <% end %>

        <% unless @beer_profile.taste_flavor_herbs.blank? %>
          <div class="tertiary-section">
            <h4>herbs</h4>
            <%= @beer_profile.taste_flavor_herbs %>
          </div>
        <% end %>

        <% unless @beer_profile.taste_flavor_funk.blank? %>
          <div class="tertiary-section">
            <h4>funk</h4>
            <%= @beer_profile.taste_flavor_funk %>
          </div>
        <% end %>

        <% unless @beer_profile.taste_flavor_mineral.blank? %>
          <div class="tertiary-section">
            <h4>mineral</h4>
            <%= @beer_profile.taste_flavor_mineral %>
          </div>
        <% end %>

        <% unless @beer_profile.taste_flavor_other.blank? %>
          <div class="tertiary-section">
            <h4>other</h4>
            <%= @beer_profile.taste_flavor_other %>
          </div>
        <% end %>
      <% end %>
      <% if taste_section_blank? %>
        No thoughts?  Tell us how your heart feels.
      <% end %>
   </div>

    <% unless @beer_profile.taste_notes.blank? %>
      <div class="secondary-section">
        <h3>Notes</h3>
        <strong>notes</strong>
        <%= @beer_profile.taste_notes %>
      </div>
    <% end %>
  </div>

  <div class="box lg5-lg8 md3-md4 sm-all">
    <h2>Mouthfeel</h2>
    <% unless @beer_profile.mouth_body.blank? %>
      <div class="secondary-section">
        <h3>body</h3>
        <%= @beer_profile.mouth_body %>
      </div>
    <% end %>

    <% unless @beer_profile.mouth_carbonation.blank? %>
      <div class="secondary-section">
        <h3>carbonation</h3>
        <%= @beer_profile.mouth_carbonation %>
      </div>
    <% end %>

    <% unless @beer_profile.mouth_alcohol.blank? %>
      <div class="secondary-section">
        <h3>alcohol</h3>
        <%= @beer_profile.mouth_alcohol %>
      </div>
    <% end %>

    <% unless @beer_profile.mouth_richness.blank? %>
      <div class="secondary-section">
        <h3>richness</h3>
        <%= @beer_profile.mouth_richness %>
      </div>
    <% end %>

    <% unless @beer_profile.mouth_astringency.blank? %>
      <div class="secondary-section">
        <h3>astringency</h3>
        <%= @beer_profile.mouth_astringency %>
      </div>
    <% end %>

    <% unless @beer_profile.mouth_finish.blank? %>
      <div class="secondary-section">
        <h3>finish</h3>
        <%= @beer_profile.mouth_finish %>
      </div>
    <% end %>

    <% unless @beer_profile.mouth_notes.blank? %>
      <div class="secondary-section">
        <h3>notes</h3>
        <%= @beer_profile.mouth_notes %>
      </div>
    <% end %>

    <% if mouthfeel_section_blank? %>
      No thoughts?  Tell us how your heart feels.
    <% end %>
  </div>
</div>

<div class="clearfix"></div>
<% if current_user.id == @beer_profile.user_id %>
  <div class="lg-all md-all sm-all clearfix">
    <div class="lg2-lg4">
      <% if @beer_profile.user_id == current_user.id %>
        <%= link_to 'Back to My Journal', beer_profiles_path, :class => "button push-effect" %>
      <% else %>
        <%= link_to 'Back', "/beer_profiles/users/" + @beer_profile.user_id.to_s, :class => "button push-effect" %>
      <% end %>
    </div>

     <div class="lg5-lg7">
      <%= link_to 'Edit this Review', edit_beer_profile_path(@beer_profile), :class => "button push-effect" %>
    </div>
  </div>
<% end %>

<br><br><br><br><br><br><br><br><br><br>


<script type="text/javascript">
  $(function(){
    chart_context = document.getElementById('flavor-wheel').getContext('2d');
    chart_data = {
      labels : ["Esters", "Alcoholic", "Citrus", "Hoppy", "Floral", "Spicy", "Malty", "Toffee", "Burnt", "Sweet", "Sour", "Bitter", "Astringent", "Full-Bodied", "Lingers"],
      datasets : [
        {
          fillColor : "rgba(220,220,220,0.5)",
          strokeColor : "rgba(220,220,220,1)",
          pointColor : "rgba(220,220,220,1)",
          pointStrokeColor : "#fff",
          data : <%= @beer_profile.flavors.to_s %>
        }
      ]
    }

    flavor_wheel = new Chart(chart_context).Radar(chart_data, {
      pointLabelFontColor: '#FFF',
      scaleLineColor: '#FFF',
      angleLineColor: '#FFF'
    });
  })
</script>

app/views/beer_profiles/users.html.erb
<% if @user.nil? %>
  <div class="errors">
    User not found
  </div>
<% else %>
  <h1>Listing Beer Profiles For <%= @user.email %></h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Brewery</th>
        <th>Style</th>
        <th>ABV</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @beer_profiles.each do |beer_profile| %>
        <tr>
          <td><%= beer_profile.name %></td>
          <td><%= beer_profile.brewery %></td>
          <td><%= beer_profile.style %></td>
          <td><%= beer_profile.abv %></td>
          <td><%= link_to 'Show', beer_profile %></td>
        </tr>
      <% end %>
      <% if @beer_profiles.count == 0 %>
        <tr>
          <td colspan='5'>
            No profiles yet for this user.
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>